server:
  port: 8010
spring:
  application:
    name: provider # 服务名，即当前服务注册在 Eureka Server 上的名字
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 注册中心访问地址，server和client都一样的地址
  instance:
    prefer-ip-address: true # 是否将当前服务的 ip 注册到 Eureka Server